### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by rishiankush** [blazerroad/react-native-azure-blob-storage#2]
This is my contructor:
```
constructor(props){
        super(props);
        initAzureBlob(
        {
            storageKey: `E/3m6oKcAp49bbB2KOrDndv9AsaIp5c08tFigMH8SIdqq++2FyH5/M7wGoY8UghhoFGUUc3kyjrLnIiiODzFaQ==`,
            account: `homvideos`,
            version: '2020-07-13'
        })
        this.state={
            profileImg:'',
            temprature:''
        }
    }
```

This is my upload image method:
```
uploadImage = async (assest) => {
        const res = await azureblobfetch({
          assest: assest,
          container: "images", //your countainer name,
          filenameprefix: "test", //add before the autogenrated file name,
          type: 'Upload'
        })
        console.log('res ******** ',res);
        Upload.addListener('progress', res.uploadId, (data) => {
          console.log(`Progress: ${data.progress}% `)
        })
        Upload.addListener('cancelled', res.uploadId, (data) => {
          console.log(`Cancelled!`)
        })
        Upload.addListener('completed', res.uploadId, (data) => {
          // data includes responseCode: number and responseBody: Object
          console.log(data)
        })
    
    }
```

And this is the error I am getting:
<img width="1289" alt="Screenshot 2020-07-13 at 10 26 42 AM" src="https://user-images.githubusercontent.com/25289937/87272427-d651bf00-c4f3-11ea-9690-1a76c4650f9a.png">

**Comment by blazerroad** [comment]
HI, could you please check your assests data, it seems the  "getFileInfo"  method has problem with assets which you pass to it

**Comment by rishiankush** [comment]
@blazerroad I am adding a path in the assets please confirm if this is the correct way:
the path looks like this: /storage/emulated/0/Pictures/images/image-e0ae97b6-0be9-48f6-bdd3-c9b5fff33477.jpg

**Comment by blazerroad** [comment]
your assets should be object with URI property like this : assest.uri

>  const metadata = await Upload.getFileInfo(param.assest.uri);

your are getting the error in this code line, you also can trace this function : 

> async azurBlobFetch(param: FetchParam)

At : 

> azurblobstorage.ts

**Comment by rishiankush** [comment]
The upload is working fine now when I passed object as you mentioned above and I am getting the response too but the app is crashing now. Here is the response I am getting:
<img width="1440" alt="Screenshot 2020-07-13 at 10 19 02 PM" src="https://user-images.githubusercontent.com/25289937/87330994-f6669a00-c556-11ea-9c4c-084cf8ef914e.png">

What I think, the the issue is with the file type, I need to pass a file type or extention something like file.jpg, or png or jpeg.
Do we have such property in this module?

**Comment by blazerroad** [comment]
if crash happend on andriod please  check the log it usually becouse of  depency package for  upload

**Comment by rishiankush** [comment]
The crash was due to the permission denial by Foreground Service.This will happen if you have set `targetSdkVersion = 28` (Android 9 / Pie) or above and have not declared the usage of the `FOREGROUND_SERVICE` permission.

My Solution: In Android Menifest file I added this permission:
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`

@blazerroad  Thanks a ton for your great help!

**Comment by Vrushabh59** [comment]
can you help me with this issue? i have same issue and same code

**Comment by blazerroad** [comment]
did u check the foreground_services permission?

**Comment by Vrushabh59** [comment]
> The upload is working fine now when I passed object as you mentioned above and I am getting the response too but the app is crashing now. Here is the response I am getting:
> <img alt="Screenshot 2020-07-13 at 10 19 02 PM" width="1440" src="https://user-images.githubusercontent.com/25289937/87330994-f6669a00-c556-11ea-9c4c-084cf8ef914e.png">
> 
> What I think, the the issue is with the file type, I need to pass a file type or extention something like file.jpg, or png or jpeg.
> Do we have such property in this module?

how you done that can you help me with code ?

**Comment by Vrushabh59** [comment]
> did u check the foreground_services permission?

yes

**Comment by Vrushabh59** [comment]
> This is my contructor:
> 
> ```
> constructor(props){
>         super(props);
>         initAzureBlob(
>         {
>             storageKey: `E/3m6oKcAp49bbB2KOrDndv9AsaIp5c08tFigMH8SIdqq++2FyH5/M7wGoY8UghhoFGUUc3kyjrLnIiiODzFaQ==`,
>             account: `homvideos`,
>             version: '2020-07-13'
>         })
>         this.state={
>             profileImg:'',
>             temprature:''
>         }
>     }
> ```
> 
> This is my upload image method:
> 
> ```
> uploadImage = async (assest) => {
>         const res = await azureblobfetch({
>           assest: assest,
>           container: "images", //your countainer name,
>           filenameprefix: "test", //add before the autogenrated file name,
>           type: 'Upload'
>         })
>         console.log('res ******** ',res);
>         Upload.addListener('progress', res.uploadId, (data) => {
>           console.log(`Progress: ${data.progress}% `)
>         })
>         Upload.addListener('cancelled', res.uploadId, (data) => {
>           console.log(`Cancelled!`)
>         })
>         Upload.addListener('completed', res.uploadId, (data) => {
>           // data includes responseCode: number and responseBody: Object
>           console.log(data)
>         })
>     
>     }
> ```
> 
> And this is the error I am getting:
> <img alt="Screenshot 2020-07-13 at 10 26 42 AM" width="1289" src="https://user-images.githubusercontent.com/25289937/87272427-d651bf00-c4f3-11ea-9690-1a76c4650f9a.png">

i have exact problem like this

**Comment by rishiankush** [comment]
The foreground services permissions are inside android/app/src/main/AndroidMenifest.xml file. please add the permission there and it will work.
My Solution: In Android Menifest file I added this permission:
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`

**Comment by Vrushabh59** [comment]
it is solved i m passing wrong object to function
