### ISSUE TITLE
Can I use this library on an Expo managed app?

### ISSUE THREAD

**Issue by ammedinap93** [blazerroad/react-native-azure-blob-storage#3]
I am following the example code given in the Doc and it is not working for me.
This is the error:
![image](https://user-images.githubusercontent.com/43796884/93660157-fdf46480-fa19-11ea-889b-eecaf28130f7.png)
NativeModule is null.
I am using Expo: Client version 2.16.1, Supported SDKs 35, 36, 37, 38.
Any help will be very appreciated.

**Comment by blazerroad** [comment]
No, because I used getFileInfo library which need pod installation and etc. so you can use it under expo
